import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { FileImage, ImagePlus, Trash2, TriangleAlert } from "lucide-react";
import { FormEvent, useState } from "react";

function fileData(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }
function ProductImages({ product }: { product: any }) { const [file, setFile] = useState<File | null>(null); const [alt, setAlt] = useState(""); const utils = trpc.useUtils(); const upload = trpc.products.uploadImage.useMutation({ onSuccess: () => void utils.products.adminList.invalidate() }); const remove = trpc.products.deleteImage.useMutation({ onSuccess: () => void utils.products.adminList.invalidate() }); async function submit(e: FormEvent) { e.preventDefault(); if (!file) return; await upload.mutateAsync({ productId: product.id, fileName: file.name, imageData: await fileData(file), altText: alt || null, sortOrder: product.images.length }); setFile(null); setAlt(""); } return <article className="rounded-xl border border-[#d4af37]/20 bg-[#0d0d12] p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="font-black">{product.name}</h2><p className="mt-1 text-xs text-[#f5f0e8]/45">{product.images.length} صورة</p></div></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{product.images.map((image: any) => <div key={image.id} className="group relative aspect-square overflow-hidden rounded-lg bg-black"><img src={image.url} alt={image.altText || product.name} className="h-full w-full object-cover" /><button aria-label="حذف الصورة" className="absolute left-2 top-2 grid h-8 w-8 place-items-center rounded-lg bg-black/80 text-rose-300 opacity-0 transition group-hover:opacity-100" onClick={() => { if (window.confirm("حذف هذه الصورة؟")) void remove.mutateAsync({ id: image.id }); }}><Trash2 className="h-4 w-4" /></button></div>)}{product.images.length === 0 && <div className="col-span-full rounded-lg border border-dashed border-[#d4af37]/25 p-5 text-center text-sm text-[#f5f0e8]/45">لم يتم رفع صور لهذا المنتج بعد.</div>}</div><form onSubmit={e => void submit(e)} className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><Input type="file" required accept="image/png,image/jpeg,image/webp" className="border-[#d4af37]/20 bg-black/25" onChange={e => setFile(e.target.files?.[0] || null)} /><Input value={alt} className="border-[#d4af37]/20 bg-black/25" placeholder="وصف الصورة (اختياري)" onChange={e => setAlt(e.target.value)} /><Button disabled={!file || upload.isPending} className="bg-gold-gradient font-black text-black"><ImagePlus className="ml-2 h-4 w-4" />{upload.isPending ? "جارٍ الرفع…" : "رفع صورة"}</Button></form></article>; }
export default function AdminMedia() { const { user, loading } = useAuth(); const products = trpc.products.adminList.useQuery(undefined, { enabled: user?.role === "admin" }); if (loading) return <div className="min-h-screen bg-[#08090d]" />; if (user?.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#08090d] p-6 text-center"><div className="rounded-xl border border-[#d4af37]/25 bg-[#0d0d12] p-8"><TriangleAlert className="mx-auto h-10 w-10 text-[#d4af37]" /><h1 className="mt-4 text-xl font-black">يلزم صلاحية مدير</h1></div></div>; return <DashboardLayout><div><p className="text-sm font-bold tracking-[.2em] text-[#d4af37]/70">مكتبة المتجر</p><h1 className="mt-2 text-4xl font-black"><span className="text-gold-gradient">صور المنتجات</span></h1><p className="mt-3 text-[#f5f0e8]/55">أضف زوايا وصورًا إضافية للمنتج، أو احذف الصور القديمة.</p><div className="mt-8 space-y-5">{products.data?.map(product => <ProductImages key={product.id} product={product} />)}{products.data?.length === 0 && <div className="rounded-xl border border-dashed border-[#d4af37]/30 p-10 text-center text-[#f5f0e8]/45">أضف منتجًا أولًا لتتمكن من إدارة صوره.</div>}</div></div></DashboardLayout>; }
