import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Pencil, Plus, Save, Trash2, TriangleAlert } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

type Form = { name: string; slug: string; description: string; sortOrder: string; isActive: boolean };
const empty: Form = { name: "", slug: "", description: "", sortOrder: "0", isActive: true };
const cls = "mt-2 w-full rounded-lg border border-[#d4af37]/20 bg-black/25 px-3 py-2.5 text-sm text-[#f5f0e8] outline-none focus:border-[#d4af37]/65";
function Editor({ category, close }: { category?: any; close: () => void }) { const [f, setF] = useState<Form>(empty); const utils = trpc.useUtils(); const create = trpc.categories.create.useMutation(); const update = trpc.categories.update.useMutation(); useEffect(() => setF(category ? { name: category.name, slug: category.slug, description: category.description || "", sortOrder: String(category.sortOrder), isActive: category.isActive } : empty), [category]); async function submit(e: FormEvent) { e.preventDefault(); const payload = { name: f.name, slug: f.slug, description: f.description || null, sortOrder: Number(f.sortOrder), isActive: f.isActive }; if (category) await update.mutateAsync({ id: category.id, ...payload }); else await create.mutateAsync(payload); await utils.categories.adminList.invalidate(); await utils.categories.list.invalidate(); close(); } return <form onSubmit={e => void submit(e)} className="mt-6 grid gap-4 rounded-xl border border-[#d4af37]/20 bg-[#0d0d12] p-5 sm:grid-cols-2"><label className="text-sm font-bold">اسم القسم<Input required className={cls} value={f.name} onChange={e => setF(v => ({ ...v, name: e.target.value, slug: category ? v.slug : e.target.value.trim().toLowerCase().replace(/\s+/g, "-") }))} /></label><label className="text-sm font-bold">الرابط المختصر (Slug)<Input required dir="ltr" className={cls} value={f.slug} onChange={e => setF(v => ({ ...v, slug: e.target.value }))} /></label><label className="text-sm font-bold sm:col-span-2">وصف القسم<Textarea className={`${cls} min-h-20`} value={f.description} onChange={e => setF(v => ({ ...v, description: e.target.value }))} /></label><label className="text-sm font-bold">ترتيب العرض<Input type="number" min="0" className={cls} value={f.sortOrder} onChange={e => setF(v => ({ ...v, sortOrder: e.target.value }))} /></label><label className="flex items-center gap-3 self-end rounded-lg border border-[#d4af37]/15 p-3 text-sm"><input type="checkbox" checked={f.isActive} onChange={e => setF(v => ({ ...v, isActive: e.target.checked }))} />ظاهر للعميل في المتجر</label><div className="flex gap-3 sm:col-span-2"><Button className="rounded-full bg-gold-gradient font-black text-black" disabled={create.isPending || update.isPending}><Save className="ml-2 h-4 w-4" />حفظ القسم</Button><Button type="button" variant="outline" className="rounded-full border-[#d4af37]/35 text-[#d4af37]" onClick={close}>إلغاء</Button></div></form>; }
export default function AdminCategories() { const { user, loading } = useAuth(); const q = trpc.categories.adminList.useQuery(undefined, { enabled: user?.role === "admin" }); const utils = trpc.useUtils(); const remove = trpc.categories.delete.useMutation({ onSuccess: () => { void utils.categories.adminList.invalidate(); void utils.categories.list.invalidate(); } }); const [edit, setEdit] = useState<any | null>(null); const [adding, setAdding] = useState(false); if (loading) return <div className="min-h-screen bg-[#08090d]" />; if (user?.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#08090d]"><TriangleAlert className="h-10 w-10 text-[#d4af37]" /></div>; return <DashboardLayout><div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-[.2em] text-[#d4af37]/70">تنظيم المتجر</p><h1 className="mt-2 text-4xl font-black"><span className="text-gold-gradient">الأقسام</span></h1><p className="mt-3 text-[#f5f0e8]/55">نظّم عرض منتجاتك وأخفِ الأقسام غير الجاهزة.</p></div><Button className="rounded-full bg-gold-gradient font-black text-black" onClick={() => { setEdit(null); setAdding(true); }}><Plus className="ml-2 h-4 w-4" />إضافة قسم</Button></div>{(adding || edit) && <Editor category={edit || undefined} close={() => { setEdit(null); setAdding(false); }} />}<div className="mt-7 overflow-hidden rounded-xl border border-[#d4af37]/20 bg-[#0d0d12]"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead className="bg-black/35 text-[#d4af37]/70"><tr><th className="p-4">الاسم</th><th className="p-4">الرابط</th><th className="p-4">الوصف</th><th className="p-4">الترتيب</th><th className="p-4">الظهور</th><th className="p-4">إجراءات</th></tr></thead><tbody>{q.data?.map(c => <tr key={c.id} className="border-t border-[#d4af37]/10"><td className="p-4 font-bold">{c.name}</td><td dir="ltr" className="p-4 text-[#f5f0e8]/45">{c.slug}</td><td className="max-w-64 truncate p-4 text-[#f5f0e8]/55">{c.description || "—"}</td><td className="p-4">{c.sortOrder}</td><td className="p-4">{c.isActive ? "ظاهر" : "مخفي"}</td><td className="p-4"><div className="flex gap-2"><Button size="sm" variant="outline" className="border-[#d4af37]/35 text-[#d4af37]" onClick={() => { setAdding(false); setEdit(c); }}><Pencil className="h-3.5 w-3.5" /></Button><Button size="sm" variant="ghost" className="text-rose-300 hover:bg-rose-500/10" onClick={() => { if (window.confirm(`حذف قسم ${c.name}؟`)) void remove.mutateAsync({ id: c.id }); }}><Trash2 className="h-3.5 w-3.5" /></Button></div></td></tr>)}{q.data?.length === 0 && <tr><td colSpan={6} className="p-10 text-center text-[#f5f0e8]/50">لا توجد أقسام. أضف قسمًا لتنظيم المنتجات.</td></tr>}</tbody></table></div></div></div></DashboardLayout>; }
