import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { formatMoney, formatOrderDate, primaryImage, statusLabel } from "@/lib/commerce";
import { trpc } from "@/lib/trpc";
import { BarChart3, CheckCircle2, Image, Package, PackagePlus, Pencil, ReceiptText, Save, Settings, ShoppingBag, Trash2, TriangleAlert } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useLocation } from "wouter";

type ProductForm = { name: string; slug: string; description: string; categoryId: string; price: string; stock: string; isActive: boolean; isFeatured: boolean };
const blank: ProductForm = { name: "", slug: "", description: "", categoryId: "", price: "", stock: "0", isActive: true, isFeatured: false };
const input = "mt-2 w-full rounded-lg border border-[#d4af37]/20 bg-black/25 px-3 py-2.5 text-sm text-[#f5f0e8] outline-none focus:border-[#d4af37]/65";

function ProductFormPanel({ editing, done }: { editing?: any; done: () => void }) {
  const [form, setForm] = useState<ProductForm>(blank); const [file, setFile] = useState<File | null>(null); const categories = trpc.categories.adminList.useQuery(); const utils = trpc.useUtils(); const create = trpc.products.create.useMutation(); const update = trpc.products.update.useMutation(); const upload = trpc.products.uploadImage.useMutation();
  useEffect(() => { setForm(editing ? { name: editing.name, slug: editing.slug, description: editing.description || "", categoryId: editing.categoryId ? String(editing.categoryId) : "", price: String(editing.priceAmount / 100), stock: String(editing.stock), isActive: editing.isActive, isFeatured: editing.isFeatured } : blank); setFile(null); }, [editing]);
  const set = <K extends keyof ProductForm>(key: K, value: ProductForm[K]) => setForm(v => ({ ...v, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); const payload = { name: form.name, slug: form.slug, description: form.description || null, categoryId: form.categoryId ? Number(form.categoryId) : null, priceAmount: Math.round(Number(form.price) * 100), stock: Number(form.stock), isActive: form.isActive, isFeatured: form.isFeatured }; const id = editing ? (await update.mutateAsync({ id: editing.id, ...payload }), editing.id) : (await create.mutateAsync(payload)).id; if (file) { const reader = new FileReader(); const data = await new Promise<string>((resolve, reject) => { reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); await upload.mutateAsync({ productId: id, fileName: file.name, imageData: data }); } await utils.products.adminList.invalidate(); done(); }
  const pending = create.isPending || update.isPending || upload.isPending;
  return <form onSubmit={e => void submit(e)} className="mt-6 grid gap-4 rounded-xl border border-[#d4af37]/20 bg-[#0d0d12] p-5 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">اسم المنتج<Input required className={input} value={form.name} onChange={e => { set("name", e.target.value); if (!editing) set("slug", e.target.value.trim().toLowerCase().replace(/\s+/g, "-")); }} /></label><label className="text-sm font-bold sm:col-span-2">الرابط المختصر (Slug)<Input required dir="ltr" className={input} value={form.slug} onChange={e => set("slug", e.target.value)} /></label><label className="text-sm font-bold sm:col-span-2">وصف المنتج<Textarea className={`${input} min-h-24`} value={form.description} onChange={e => set("description", e.target.value)} /></label><label className="text-sm font-bold">القسم<select className={input} value={form.categoryId} onChange={e => set("categoryId", e.target.value)}><option value="">بدون قسم</option>{categories.data?.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm font-bold">السعر (ج.م)<Input required type="number" min="0" step="0.01" className={input} value={form.price} onChange={e => set("price", e.target.value)} /></label><label className="text-sm font-bold">المخزون<Input required type="number" min="0" className={input} value={form.stock} onChange={e => set("stock", e.target.value)} /></label><label className="text-sm font-bold">الصورة الرئيسية<Input type="file" accept="image/png,image/jpeg,image/webp" className={input} onChange={e => setFile(e.target.files?.[0] || null)} /></label><label className="flex items-center gap-3 rounded-lg border border-[#d4af37]/15 p-3 text-sm"><input type="checkbox" checked={form.isActive} onChange={e => set("isActive", e.target.checked)} />ظاهر في المتجر</label><label className="flex items-center gap-3 rounded-lg border border-[#d4af37]/15 p-3 text-sm"><input type="checkbox" checked={form.isFeatured} onChange={e => set("isFeatured", e.target.checked)} />منتج مميز</label><div className="flex gap-3 sm:col-span-2"><Button type="submit" disabled={pending} className="rounded-full bg-gold-gradient font-black text-black">{pending ? "جارٍ الحفظ…" : editing ? "حفظ التعديلات" : "إضافة المنتج"}</Button><Button type="button" variant="outline" className="rounded-full border-[#d4af37]/35 text-[#d4af37]" onClick={done}>إلغاء</Button></div></form>;
}

function Overview() { const q = trpc.admin.dashboard.useQuery(); const cards = q.data ? [[ShoppingBag, "إجمالي الطلبات", q.data.totalOrders], [BarChart3, "إجمالي المبيعات", formatMoney(q.data.revenueAmount)], [ReceiptText, "طلبات قيد المراجعة", q.data.pendingOrders]] : []; return <div><p className="text-sm font-bold tracking-[.2em] text-[#d4af37]/70">إدارة المتجر</p><h1 className="mt-2 text-4xl font-black"><span className="text-gold-gradient">نظرة عامة</span></h1><p className="mt-3 text-[#f5f0e8]/55">ملخص نشاط المتجر والطلبات والمنتجات الأكثر طلبًا.</p><div className="mt-8 grid gap-4 md:grid-cols-3">{cards.map(([Icon, label, value]) => { const C = Icon as typeof ShoppingBag; return <div key={String(label)} className="rounded-xl border border-[#d4af37]/20 bg-[#0d0d12] p-5"><C className="h-5 w-5 text-[#d4af37]" /><p className="mt-5 text-2xl font-black">{value as string | number}</p><p className="mt-1 text-sm text-[#f5f0e8]/50">{label as string}</p></div>; })}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-[#d4af37]/20 bg-[#0d0d12] p-5"><h2 className="font-black text-[#d4af37]">المنتجات الأكثر طلبًا</h2><div className="mt-4 space-y-3">{q.data?.topProducts.map((p, i) => <div key={p.productName} className="flex items-center justify-between rounded-lg bg-black/25 p-3"><span className="font-bold"><span className="ml-2 text-[#d4af37]">{i + 1}</span>{p.productName}</span><span className="text-sm text-[#f5f0e8]/50">{p.quantity} قطعة</span></div>) || <p className="text-sm text-[#f5f0e8]/45">لا توجد بيانات حتى الآن.</p>}</div></section><section className="rounded-xl border border-[#d4af37]/20 bg-[#0d0d12] p-5"><h2 className="font-black text-[#d4af37]">أحدث الطلبات</h2><div className="mt-4 space-y-3">{q.data?.recentOrders.map(o => <div key={o.id} className="flex items-center justify-between rounded-lg bg-black/25 p-3"><div><p className="font-bold">{o.orderNumber}</p><p className="mt-1 text-xs text-[#f5f0e8]/45">{o.customerName}</p></div><div className="text-left"><p className="font-bold text-[#d4af37]">{formatMoney(o.totalAmount)}</p><p className="mt-1 text-xs text-[#f5f0e8]/45">{statusLabel(o.status)}</p></div></div>) || <p className="text-sm text-[#f5f0e8]/45">لا توجد طلبات حتى الآن.</p>}</div></section></div></div>; }

function Products() { const q = trpc.products.adminList.useQuery(); const utils = trpc.useUtils(); const remove = trpc.products.delete.useMutation({ onSuccess: () => void utils.products.adminList.invalidate() }); const [editing, setEditing] = useState<any | undefined>(); const [newOpen, setNewOpen] = useState(false); return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-[.2em] text-[#d4af37]/70">إدارة الكتالوج</p><h1 className="mt-2 text-4xl font-black"><span className="text-gold-gradient">المنتجات</span></h1><p className="mt-3 text-[#f5f0e8]/55">أضف المنتجات وعدّل السعر والمخزون والصور بسهولة.</p></div><Button className="rounded-full bg-gold-gradient font-black text-black" onClick={() => { setEditing(undefined); setNewOpen(true); }}><PackagePlus className="ml-2 h-4 w-4" />إضافة منتج</Button></div>{(newOpen || editing) && <ProductFormPanel editing={editing} done={() => { setEditing(undefined); setNewOpen(false); }} />}<div className="mt-7 overflow-hidden rounded-xl border border-[#d4af37]/20 bg-[#0d0d12]"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-right text-sm"><thead className="bg-black/35 text-[#d4af37]/70"><tr><th className="p-4">المنتج</th><th className="p-4">القسم</th><th className="p-4">السعر</th><th className="p-4">المخزون</th><th className="p-4">الحالة</th><th className="p-4">إجراءات</th></tr></thead><tbody>{q.data?.map(p => <tr key={p.id} className="border-t border-[#d4af37]/10"><td className="p-4"><div className="flex items-center gap-3"><img src={primaryImage(p.images)} alt="" className="h-11 w-11 rounded-lg object-cover" /><div><p className="font-bold">{p.name}</p><p dir="ltr" className="mt-1 text-xs text-[#f5f0e8]/40">{p.slug}</p></div></div></td><td className="p-4 text-[#f5f0e8]/60">{p.category?.name || "—"}</td><td className="p-4 font-bold text-[#d4af37]">{formatMoney(p.priceAmount)}</td><td className="p-4">{p.stock}</td><td className="p-4 text-xs">{p.isActive ? "ظاهر" : "مخفي"}</td><td className="p-4"><div className="flex gap-2"><Button size="sm" variant="outline" className="border-[#d4af37]/35 text-[#d4af37]" onClick={() => { setNewOpen(false); setEditing(p); }}><Pencil className="h-3.5 w-3.5" /></Button><Button size="sm" variant="ghost" className="text-rose-300 hover:bg-rose-500/10 hover:text-rose-200" onClick={() => { if (window.confirm(`حذف ${p.name}؟`)) void remove.mutateAsync({ id: p.id }); }}><Trash2 className="h-3.5 w-3.5" /></Button></div></td></tr>)}{q.data?.length === 0 && <tr><td colSpan={6} className="p-10 text-center text-[#f5f0e8]/50">لا توجد منتجات. أضف أول منتج لعرضه في المتجر.</td></tr>}</tbody></table></div></div></div>; }

function AdminOrders() { const q = trpc.admin.orders.useQuery(); const utils = trpc.useUtils(); const update = trpc.admin.updateOrder.useMutation({ onSuccess: () => { void utils.admin.orders.invalidate(); void utils.admin.dashboard.invalidate(); } }); return <div><p className="text-sm font-bold tracking-[.2em] text-[#d4af37]/70">التحضير والتسليم</p><h1 className="mt-2 text-4xl font-black"><span className="text-gold-gradient">الطلبات</span></h1><div className="mt-8 space-y-4">{q.data?.map(o => <article key={o.id} className="rounded-xl border border-[#d4af37]/20 bg-[#0d0d12] p-5"><div className="flex flex-col justify-between gap-5 lg:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{o.orderNumber}</h2><span className="rounded-full bg-[#d4af37]/10 px-2 py-1 text-xs text-[#d4af37]">{statusLabel(o.status)}</span></div><p className="mt-3 text-sm text-[#f5f0e8]/60">{o.customerName} · {o.customerPhone} · {formatOrderDate(o.createdAt)}</p><p className="mt-1 text-sm text-[#f5f0e8]/45">{o.shippingAddress}</p><p className="mt-3 font-black text-[#d4af37]">{formatMoney(o.totalAmount)} · {o.paymentMethod === "instapay" ? "InstaPay" : "عند الاستلام"}</p></div><div className="grid gap-2 sm:grid-cols-2 lg:w-80"><select className={input} value={o.status} onChange={e => void update.mutateAsync({ id: o.id, status: e.target.value as any })}>{["pending","confirmed","shipped","delivered","cancelled"].map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select>{o.paymentMethod === "instapay" && <select className={input} value={o.paymentStatus} onChange={e => void update.mutateAsync({ id: o.id, paymentStatus: e.target.value as any })}>{["awaiting_proof","under_review","verified","rejected"].map(s => <option key={s} value={s}>{statusLabel(s)}</option>)}</select>}</div></div><div className="mt-4 border-t border-[#d4af37]/10 pt-4 text-sm text-[#f5f0e8]/60"><p>{o.items.map(i => `${i.quantity}× ${i.productName}`).join(" · ")}</p>{o.paymentProofs.map(p => <a key={p.id} href={p.url} target="_blank" rel="noreferrer" className="mt-3 inline-flex rounded-lg border border-[#d4af37]/25 px-3 py-2 text-xs font-bold text-[#d4af37]">عرض إثبات التحويل: {p.originalFilename}</a>)}</div></article>)}{q.data?.length === 0 && <div className="rounded-xl border border-dashed border-[#d4af37]/30 p-10 text-center text-[#f5f0e8]/50">ستظهر الطلبات هنا بعد إتمام الشراء.</div>}</div></div>; }

function SettingsPage() { const q = trpc.admin.storeSettings.useQuery(); const update = trpc.admin.updateStoreSettings.useMutation(); const [f, setF] = useState({ storeName: "", whatsappNumber: "", instaPayHandle: "", shippingFee: "0" }); useEffect(() => { if (q.data) setF({ storeName: q.data.storeName, whatsappNumber: q.data.whatsappNumber, instaPayHandle: q.data.instaPayHandle || "", shippingFee: String(q.data.shippingFeeAmount / 100) }); }, [q.data]); async function save(e: FormEvent) { e.preventDefault(); await update.mutateAsync({ storeName: f.storeName, whatsappNumber: f.whatsappNumber, instaPayHandle: f.instaPayHandle || null, shippingFeeAmount: Math.round(Number(f.shippingFee) * 100) }); } return <div><p className="text-sm font-bold tracking-[.2em] text-[#d4af37]/70">إعدادات التشغيل</p><h1 className="mt-2 text-4xl font-black"><span className="text-gold-gradient">إعدادات المتجر</span></h1><form onSubmit={e => void save(e)} className="mt-8 max-w-2xl rounded-xl border border-[#d4af37]/20 bg-[#0d0d12] p-6"><label className="block text-sm font-bold">اسم المتجر<Input required className={input} value={f.storeName} onChange={e => setF(v => ({ ...v, storeName: e.target.value }))} /></label><label className="mt-5 block text-sm font-bold">رقم واتساب (بالصيغة الدولية)<Input required dir="ltr" className={input} value={f.whatsappNumber} onChange={e => setF(v => ({ ...v, whatsappNumber: e.target.value }))} placeholder="201020848619" /></label><label className="mt-5 block text-sm font-bold">معرّف InstaPay <span className="font-normal text-[#f5f0e8]/45">(اختياري)</span><Input dir="ltr" className={input} value={f.instaPayHandle} onChange={e => setF(v => ({ ...v, instaPayHandle: e.target.value }))} /></label><label className="mt-5 block text-sm font-bold">رسوم التوصيل (ج.م)<Input required type="number" min="0" step="0.01" className={input} value={f.shippingFee} onChange={e => setF(v => ({ ...v, shippingFee: e.target.value }))} /></label>{update.isSuccess && <p className="mt-5 flex items-center gap-2 text-sm text-emerald-300"><CheckCircle2 className="h-4 w-4" />تم حفظ الإعدادات.</p>}<Button className="mt-6 rounded-full bg-gold-gradient font-black text-black" disabled={update.isPending}><Save className="ml-2 h-4 w-4" />{update.isPending ? "جارٍ الحفظ…" : "حفظ الإعدادات"}</Button></form></div>; }

export default function AdminDashboard() { const { user, loading } = useAuth(); const [loc] = useLocation(); if (loading) return <div className="min-h-screen bg-[#08090d]" />; if (user?.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#08090d] p-6 text-center"><div className="rounded-xl border border-[#d4af37]/25 bg-[#0d0d12] p-8"><TriangleAlert className="mx-auto h-10 w-10 text-[#d4af37]" /><h1 className="mt-4 text-xl font-black">يلزم صلاحية مدير</h1><p className="mt-2 text-sm text-[#f5f0e8]/60">لا يملك هذا الحساب صلاحية إدارة المتجر.</p></div></div>; const page = loc === "/admin/products" ? <Products /> : loc === "/admin/orders" ? <AdminOrders /> : loc === "/admin/settings" ? <SettingsPage /> : <Overview />; return <DashboardLayout>{page}</DashboardLayout>; }
