import StoreLayout from "@/components/StoreLayout";
import { Button } from "@/components/ui/button";
import { useCart } from "@/contexts/CartContext";
import { formatMoney } from "@/lib/commerce";
import { ArrowRight, Minus, Plus, Trash2 } from "lucide-react";
import { Link } from "wouter";

export default function Cart() {
  const { items, subtotalAmount, updateQuantity, removeItem } = useCart();
  return <StoreLayout><main className="container py-10 sm:py-14"><h1 className="text-4xl font-semibold tracking-tight">Your cart</h1>{items.length === 0 ? <div className="mt-8 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><h2 className="text-lg font-semibold">Your cart is empty</h2><p className="mt-2 text-sm text-slate-500">Browse the catalog to add products.</p><Link href="/shop"><Button className="mt-5">Browse catalog</Button></Link></div> : <div className="mt-8 grid gap-7 lg:grid-cols-[1fr_360px]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{items.map(item => <article key={item.productId} className="flex gap-4 border-b border-slate-100 p-4 last:border-0 sm:p-5"><Link href={`/products/${item.slug}`} className="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-slate-100"><img src={item.imageUrl} alt={item.name} className="h-full w-full object-cover" /></Link><div className="min-w-0 flex-1"><Link href={`/products/${item.slug}`} className="font-semibold hover:text-amber-700">{item.name}</Link><p className="mt-1 text-sm text-amber-700">{formatMoney(item.priceAmount)}</p><div className="mt-3 flex items-center justify-between"><div className="flex h-9 items-center rounded-lg border border-slate-200"><button aria-label="Decrease quantity" className="grid h-full w-8 place-items-center hover:bg-slate-50" onClick={() => updateQuantity(item.productId, item.quantity - 1)}><Minus className="h-3.5 w-3.5" /></button><span className="w-8 text-center text-sm font-semibold">{item.quantity}</span><button aria-label="Increase quantity" className="grid h-full w-8 place-items-center hover:bg-slate-50 disabled:opacity-40" disabled={item.quantity >= item.stock} onClick={() => updateQuantity(item.productId, item.quantity + 1)}><Plus className="h-3.5 w-3.5" /></button></div><button aria-label={`Remove ${item.name}`} className="grid h-9 w-9 place-items-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={() => removeItem(item.productId)}><Trash2 className="h-4 w-4" /></button></div></div><p className="hidden pt-1 font-semibold sm:block">{formatMoney(item.priceAmount * item.quantity)}</p></article>)}</section><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Order summary</h2><div className="mt-5 flex justify-between text-sm text-slate-600"><span>Subtotal</span><span>{formatMoney(subtotalAmount)}</span></div><p className="mt-3 text-xs leading-5 text-slate-500">Delivery pricing is shown at checkout after the store settings are applied.</p><div className="my-5 border-t border-slate-100" /><div className="flex justify-between font-semibold"><span>Products total</span><span>{formatMoney(subtotalAmount)}</span></div><Link href="/checkout" className="mt-5 block"><Button className="w-full">Continue to checkout <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></aside></div>}</main></StoreLayout>;
}
