import StoreLayout from "@/components/StoreLayout";
import { Button } from "@/components/ui/button";
import { useCart } from "@/contexts/CartContext";
import { formatMoney, primaryImage } from "@/lib/commerce";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, ChevronLeft, MessageCircle, Phone, ShieldCheck, ShoppingCart, Truck, Wrench } from "lucide-react";
import { Link } from "wouter";

const HERO = "/manus-storage/hero-bg_5f0714c2_cab5298c.jpg";
const LOGO = "/manus-storage/pasted_file_nStI0h_WhatsAppImage2026-08-01at8.25.58PM_d193407d_32f06135.jpeg";
const CATEGORY_IMAGE = "/manus-storage/category-banner_dbe4fbaa_df28b4b8.jpg";
const ABOUT_IMAGE = "/manus-storage/about-section_2b2aaa4a (1)_766be0ec.jpg";

export default function Home() {
  const products = trpc.products.list.useQuery({ page: 1, limit: 6 });
  const categories = trpc.categories.list.useQuery();
  const { addItem } = useCart();
  return <StoreLayout>
    <main>
      <section className="relative isolate min-h-[calc(100svh-72px)] overflow-hidden bg-black">
        <img src={HERO} alt="إكسسوارات زجاج موسى" className="absolute inset-0 z-0 h-full w-full object-cover object-[56%_center] opacity-70 md:object-center" />
        <div className="absolute inset-0 z-[1] bg-gradient-to-l from-black/90 via-black/70 to-black/40" />
        <div className="absolute left-12 top-16 hidden h-24 w-24 rotate-45 border border-[#d4af37]/25 lg:block" /><div className="absolute bottom-20 right-16 hidden h-40 w-40 rounded-full border border-[#d4af37]/15 lg:block" />
        <div className="container relative flex min-h-[calc(100svh-72px)] items-center py-16 md:py-20" style={{ zIndex: 20 }}><div className="max-w-2xl">
          <div className="mb-8 flex items-center gap-3"><img src={LOGO} alt="موسى" className="h-14 w-14 rounded-full object-cover ring-2 ring-[#d4af37]/55" /><div><p className="text-gold-gradient text-3xl font-black">موسى</p><p className="text-xs text-[#f5f0e8]/55">لجميع أنواع إكسسوارات الزجاج</p></div></div>
          <h1 className="text-4xl font-black leading-tight text-[#f5f0e8] sm:text-5xl md:text-7xl">جودة لا تُضاهى<br /><span className="text-gold-gradient">في كل تفصيلة</span></h1>
          <p className="mt-6 max-w-xl text-base leading-8 text-[#f5f0e8]/75 sm:text-lg md:mt-7 md:text-xl">مقابض، مفصلات، كوالين وإكسسوارات تركيب الزجاج بأعلى معايير الجودة. خدمة قريبة منك في الغردقة والبحر الأحمر.</p>
          <div className="mt-10 flex flex-wrap gap-4"><Link href="/shop"><Button className="h-13 rounded-full bg-gold-gradient px-7 text-base font-black text-black hover:opacity-90">تصفح المنتجات <ArrowLeft className="mr-2 h-5 w-5" /></Button></Link><a href="tel:01020848619"><Button variant="outline" className="h-13 rounded-full border-[#d4af37]/50 bg-black/20 px-7 text-base text-[#d4af37] hover:bg-[#d4af37]/10 hover:text-[#f5f0e8]"><Phone className="ml-2 h-5 w-5" />اتصل الآن</Button></a></div>
        </div></div>
      </section>

      <section className="border-y border-[#d4af37]/15 bg-[#0d0d12] py-20"><div className="container"><div className="text-center"><span className="text-sm font-bold tracking-[.22em] text-[#d4af37]/70">الأقسام</span><h2 className="mt-3 text-4xl font-black md:text-5xl"><span className="text-gold-gradient">كل ما تحتاجه للزجاج</span></h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{categories.data?.slice(0, 4).map(category => <Link key={category.id} href={`/shop?category=${category.slug}`} className="group relative overflow-hidden rounded-xl border border-[#d4af37]/15 bg-black/40 p-6 transition hover:-translate-y-1 hover:border-[#d4af37]/45"><img src={CATEGORY_IMAGE} alt="" className="absolute inset-0 h-full w-full object-cover opacity-15 transition duration-500 group-hover:scale-110 group-hover:opacity-25" /><div className="relative"><p className="text-2xl font-black text-[#f5f0e8] group-hover:text-[#d4af37]">{category.name}</p><p className="mt-2 text-sm text-[#f5f0e8]/50">تصفح المجموعة</p><ChevronLeft className="mt-6 h-5 w-5 text-[#d4af37]" /></div></Link>)}{!categories.data?.length && <Link href="/admin/categories" className="rounded-xl border border-dashed border-[#d4af37]/30 p-8 text-center text-[#f5f0e8]/55"><p className="font-bold text-[#d4af37]">سيظهر هنا تصنيف المنتجات</p><p className="mt-2 text-sm">أضف الأقسام من لوحة الإدارة.</p></Link>}</div></div></section>

      <section className="relative overflow-hidden bg-[#08090d] py-24"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(212,175,55,.08),transparent_28%)]" /><div className="container relative"><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="text-sm font-bold tracking-[.22em] text-[#d4af37]/70">اختياراتنا</span><h2 className="mt-3 text-4xl font-black md:text-5xl"><span className="text-gold-gradient">منتجاتنا المميزة</span></h2><p className="mt-4 text-[#f5f0e8]/55">منتجات مختارة بعناية من أفضل الخامات.</p></div><Link href="/shop" className="inline-flex items-center gap-2 text-sm font-bold text-[#d4af37] hover:text-[#f5f0e8]">عرض كل المنتجات <ArrowLeft size={18} /></Link></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.data?.products.map(product => <article key={product.id} className="group overflow-hidden rounded-xl border border-[#d4af37]/15 bg-[#0d0d12] transition hover:-translate-y-1 hover:border-[#d4af37]/40"><Link href={`/products/${product.slug}`} className="block h-64 overflow-hidden"><img src={primaryImage(product.images)} alt={product.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></Link><div className="p-5"><p className="text-xs font-semibold text-[#d4af37]/65">{product.category?.name || "إكسسوارات زجاج"}</p><Link href={`/products/${product.slug}`} className="mt-1 block text-lg font-black text-[#f5f0e8] hover:text-[#d4af37]">{product.name}</Link><div className="mt-5 flex items-center justify-between gap-3"><span className="text-xl font-black text-[#d4af37]">{formatMoney(product.priceAmount)}</span><Button disabled={product.stock < 1} className="rounded-full bg-[#d4af37] text-black hover:bg-[#f0d369]" onClick={() => addItem({ productId: product.id, slug: product.slug, name: product.name, priceAmount: product.priceAmount, imageUrl: primaryImage(product.images), stock: product.stock })}><ShoppingCart className="ml-2 h-4 w-4" />أضف للسلة</Button></div></div></article>)}{!products.data?.products.length && <div className="col-span-full rounded-xl border border-dashed border-[#d4af37]/30 p-12 text-center text-[#f5f0e8]/60">أضف منتجاتك من لوحة الإدارة لتظهر في هذه المساحة.</div>}</div></div></section>

      <section className="bg-[#0d0d12] py-20"><div className="container grid items-center gap-12 lg:grid-cols-2"><img src={ABOUT_IMAGE} alt="إكسسوارات زجاج عالية الجودة" className="h-full min-h-[330px] w-full rounded-xl object-cover ring-1 ring-[#d4af37]/20" /><div><span className="text-sm font-bold tracking-[.22em] text-[#d4af37]/70">لماذا موسى؟</span><h2 className="mt-3 text-4xl font-black leading-tight md:text-5xl">خبرة واهتمام<br /><span className="text-gold-gradient">بكل تفصيلة</span></h2><p className="mt-6 leading-8 text-[#f5f0e8]/65">نساعد أصحاب الأعمال والفنيين على اختيار إكسسوارات الزجاج المناسبة، مع تجربة طلب واضحة ومتابعة مباشرة على واتساب.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{[[ShieldCheck,"جودة موثوقة"],[Truck,"متابعة للطلب"],[Wrench,"حلول عملية"],[MessageCircle,"دعم مباشر"]].map(([Icon,label]) => { const I = Icon as typeof ShieldCheck; return <div key={label as string} className="flex items-center gap-3 rounded-lg border border-[#d4af37]/15 bg-black/25 p-4"><I className="h-5 w-5 text-[#d4af37]" /><span className="font-bold">{label as string}</span></div>; })}</div></div></div></section>

      <section className="border-t border-[#d4af37]/15 bg-black py-16 text-center"><div className="container"><p className="text-3xl font-black text-[#f5f0e8]">جاهز لطلب إكسسوارات الزجاج؟</p><p className="mt-3 text-[#f5f0e8]/60">تواصل معنا مباشرة أو تصفح المنتجات المتاحة الآن.</p><div className="mt-7 flex justify-center gap-4"><Link href="/shop"><Button className="rounded-full bg-gold-gradient px-7 font-black text-black">المتجر <ArrowLeft className="mr-2 h-4 w-4" /></Button></Link><a href="https://wa.me/201020848619" target="_blank" rel="noreferrer"><Button variant="outline" className="rounded-full border-[#d4af37]/40 text-[#d4af37] hover:bg-[#d4af37]/10 hover:text-[#f5f0e8]"><MessageCircle className="ml-2 h-4 w-4" />واتساب</Button></a></div></div></section>
    </main>
  </StoreLayout>;
}
