import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import StoreLayout from "@/components/StoreLayout";
import { Button } from "@/components/ui/button";
import { formatMoney, formatOrderDate, statusLabel } from "@/lib/commerce";
import { trpc } from "@/lib/trpc";
import { ExternalLink, FileUp, PackageSearch } from "lucide-react";

function readFile(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Unable to read the image.")); reader.readAsDataURL(file); }); }

export default function Orders() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const orders = trpc.orders.mine.useQuery(undefined, { enabled: Boolean(user) });
  const upload = trpc.orders.uploadPaymentProof.useMutation({ onSuccess: () => void utils.orders.mine.invalidate() });
  async function uploadProof(orderId: number, file: File) { const imageData = await readFile(file); const result = await upload.mutateAsync({ id: orderId, fileName: file.name, imageData }); window.open(result.whatsappUrl, "_blank", "noopener,noreferrer"); }
  if (!loading && !user) return <StoreLayout><main className="container py-20"><div className="mx-auto max-w-lg rounded-3xl border border-slate-200 bg-white p-8 text-center"><PackageSearch className="mx-auto h-10 w-10 text-amber-700" /><h1 className="mt-4 text-2xl font-semibold">Sign in to view your orders</h1><p className="mt-2 text-sm leading-6 text-slate-500">Your order history and payment proof uploads are linked to your secure account.</p><Button className="mt-6" onClick={() => startLogin()}>Sign in</Button></div></main></StoreLayout>;
  return <StoreLayout><main className="container py-10 sm:py-14"><h1 className="text-4xl font-semibold tracking-tight">My orders</h1><p className="mt-2 text-slate-600">Track the current state of your orders and upload an InstaPay transfer proof when needed.</p><div className="mt-8 space-y-4">{orders.isLoading && Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-36 animate-pulse rounded-2xl bg-slate-200" />)}{orders.data?.map(order => <article key={order.id} className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{order.orderNumber}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{statusLabel(order.status)}</span>{order.paymentMethod === "instapay" && <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-800">Payment: {statusLabel(order.paymentStatus)}</span>}</div><p className="mt-2 text-sm text-slate-500">Placed {formatOrderDate(order.createdAt)} · {order.items.length} item{order.items.length === 1 ? "" : "s"}</p><p className="mt-3 font-semibold text-amber-700">{formatMoney(order.totalAmount)}</p></div>{order.paymentMethod === "instapay" && order.paymentStatus !== "verified" && order.status !== "cancelled" && <label className="inline-flex h-10 cursor-pointer items-center justify-center rounded-lg border border-slate-200 px-4 text-sm font-medium hover:bg-slate-50"><FileUp className="mr-2 h-4 w-4" />{upload.isPending ? "Uploading…" : "Upload payment proof"}<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" disabled={upload.isPending} onChange={event => { const file = event.target.files?.[0]; if (file) void uploadProof(order.id, file); }} /></label>}</div><div className="mt-5 border-t border-slate-100 pt-4 text-sm text-slate-600"><p className="font-medium text-slate-800">Items</p><p className="mt-1 line-clamp-2">{order.items.map(item => `${item.quantity}× ${item.productName}`).join(" · ")}</p>{order.paymentProofs.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{order.paymentProofs.map(proof => <a key={proof.id} href={proof.url} target="_blank" rel="noreferrer" className="inline-flex items-center text-xs font-medium text-amber-700 hover:text-amber-800">View uploaded proof <ExternalLink className="ml-1 h-3.5 w-3.5" /></a>)}</div>}</div>{upload.error && <p className="mt-4 rounded-lg bg-rose-50 p-3 text-xs text-rose-700">{upload.error.message}</p>}</article>)}{!orders.isLoading && orders.data?.length === 0 && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><h2 className="font-semibold">No orders yet</h2><p className="mt-2 text-sm text-slate-500">Your completed checkouts will be listed here.</p></div>}</div></main></StoreLayout>;
}

