import StoreLayout from "@/components/StoreLayout";
import { Button } from "@/components/ui/button";
import { useCart } from "@/contexts/CartContext";
import { formatMoney, primaryImage } from "@/lib/commerce";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Check, Minus, Plus, ShoppingCart } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "wouter";

export default function ProductDetail() {
  const { slug } = useParams<{ slug: string }>();
  const { data: product, isLoading } = trpc.products.bySlug.useQuery({ slug });
  const [quantity, setQuantity] = useState(1);
  const { addItem } = useCart();
  if (isLoading) return <StoreLayout><main className="container py-14"><div className="h-96 animate-pulse rounded-xl bg-[#16161d]" /></main></StoreLayout>;
  if (!product) return <StoreLayout><main className="container py-20 text-center"><h1 className="text-2xl font-black">المنتج غير موجود</h1><Link href="/shop"><Button variant="outline" className="mt-5 border-[#d4af37]/40 text-[#d4af37]">العودة للمتجر</Button></Link></main></StoreLayout>;
  const image = primaryImage(product.images);
  return <StoreLayout><main className="min-h-[70vh] bg-[#08090d] py-10 sm:py-14"><div className="container"><Link href="/shop" className="inline-flex items-center gap-1 text-sm font-bold text-[#d4af37] hover:text-[#f5f0e8]"><ArrowRight className="h-4 w-4" />العودة للمتجر</Link><div className="mt-7 grid gap-9 lg:grid-cols-[1.05fr_.95fr]"><div className="overflow-hidden rounded-xl border border-[#d4af37]/15 bg-black"><img src={image} alt={product.name} className="aspect-square h-full w-full object-cover" /></div><section className="flex flex-col justify-center"><p className="text-sm font-bold text-[#d4af37]/70">{product.category?.name || "إكسسوارات زجاج"}</p><h1 className="mt-3 text-4xl font-black leading-tight text-[#f5f0e8]">{product.name}</h1><p className="mt-5 text-3xl font-black text-[#d4af37]">{formatMoney(product.priceAmount)}</p><p className="mt-7 whitespace-pre-wrap leading-8 text-[#f5f0e8]/65">{product.description || "تواصل معنا لمساعدتك في اختيار المقاس أو التكوين المناسب."}</p><div className="mt-7"><span className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-sm font-bold ${product.stock > 0 ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-300" : "border-rose-400/25 bg-rose-400/10 text-rose-300"}`}><Check className="h-4 w-4" />{product.stock > 0 ? `متوفر في المخزون: ${product.stock}` : "غير متوفر حاليًا"}</span></div>{product.stock > 0 && <div className="mt-8 flex flex-col gap-3 sm:flex-row"><div className="flex h-12 items-center rounded-lg border border-[#d4af37]/20 bg-black/30"><button aria-label="تقليل الكمية" className="grid h-full w-11 place-items-center hover:bg-[#d4af37]/10" onClick={() => setQuantity(value => Math.max(1, value - 1))}><Minus className="h-4 w-4" /></button><span className="w-10 text-center font-bold">{quantity}</span><button aria-label="زيادة الكمية" className="grid h-full w-11 place-items-center hover:bg-[#d4af37]/10" onClick={() => setQuantity(value => Math.min(product.stock, value + 1))}><Plus className="h-4 w-4" /></button></div><Button size="lg" className="flex-1 rounded-full bg-gold-gradient font-black text-black hover:opacity-90" onClick={() => addItem({ productId: product.id, slug: product.slug, name: product.name, priceAmount: product.priceAmount, imageUrl: image, stock: product.stock }, quantity)}><ShoppingCart className="ml-2 h-5 w-5" />أضف {quantity} إلى السلة</Button></div>}<div className="mt-8 rounded-xl border border-[#d4af37]/15 bg-[#0d0d12] p-5 text-sm leading-7 text-[#f5f0e8]/60">الدفع متاح عند الاستلام أو بتحويل InstaPay مع رفع صورة إثبات التحويل. سيتم تأكيد طلبك مباشرة عبر واتساب.</div></section></div></div></main></StoreLayout>;
}
